# Generated by Django 6.1 on 2026-09-03 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_business_latitude_business_longitude_and_more'),
        ('payments', '0001_initial'),
        ('reservations', '0002_reservation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='restaurant_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='restaurant_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='businesses.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation'),
        ),
    ]
