# Generated by Django 6.1 on 2026-09-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_bakerycategory_bakeryexpense_bakeryingredient_and_more'),
        ('payments', '0002_payment_restaurant_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bakery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.bakeryorder'),
        ),
    ]
