# Generated by Django 6.1 on 2026-09-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_pubbarcategory_pubbarorder_pubbarproduct_and_more'),
        ('payments', '0003_payment_bakery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pub_bar_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.pubbarorder'),
        ),
    ]
