# Generated by Django 6.1 on 2026-09-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_boutiquecategory_boutiqueorder_boutiqueproduct_and_more'),
        ('payments', '0004_payment_pub_bar_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='boutique_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.boutiqueorder'),
        ),
    ]
