# Generated by Django 6.1 on 2026-08-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='business',
            name='business_model',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('retail', 'Retail Shop'), ('wholesale', 'Wholesale'), ('salon', 'Salon & Beauty'), ('transport', 'Transport'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
    ]
