# Generated by Django 6.1 on 2026-08-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_remove_business_business_type_remove_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_model',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('motel', 'Motel'), ('lodge', 'Lodge'), ('guest_house', 'Guest House'), ('restaurant', 'Restaurant'), ('bakery', 'Bakery'), ('pub_bar', 'Pub / Bar'), ('boutique', 'Boutique')], max_length=50, null=True),
        ),
    ]
