# Generated by Django 6.1 on 2026-08-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_business_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='user_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
