# Generated by Django 6.1 on 2026-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_customer_menucategory_menuitem_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
