# Generated by Django 6.1 on 2026-09-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0007_business_latitude_business_longitude_and_more'),
        ('reservations', '0002_reservation_customer'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_activities', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LodgePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_packages', to='businesses.business')),
                ('included_activities', models.ManyToManyField(blank=True, related_name='packages', to='lodge.lodgeactivity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LodgeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('cabin', 'Cabin'), ('chalet', 'Chalet'), ('lodge_room', 'Lodge Room'), ('family_unit', 'Family Unit')], default='lodge_room', max_length=20)),
                ('view_description', models.CharField(blank=True, max_length=255)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_units', to='businesses.business')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_unit', to='rooms.room')),
            ],
            options={
                'ordering': ['room__room_number'],
            },
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lodge.lodgepackage')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_package_bookings', to='reservations.reservation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lodgeactivity',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_lodge_activity_name'),
        ),
        migrations.AddConstraint(
            model_name='lodgepackage',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_lodge_package_name'),
        ),
        migrations.AddConstraint(
            model_name='packagebooking',
            constraint=models.UniqueConstraint(fields=('reservation', 'package'), name='unique_lodge_package_booking'),
        ),
    ]
