# Generated by Django 6.1 on 2026-09-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssettings',
            options={'permissions': [('view_reports', 'Can view business reports')]},
        ),
    ]
